### ISSUE TITLE
Replace use of arr_to_plasma() with visualize()

### ISSUE THREAD

**Issue by tylere** [fusedio/udfs#318]
Replace [public/common/utils.py arr_to_plasma()](https://github.com/fusedio/udfs/blob/98263fcf8fdade1fd2e29a2c65ca5f494e2888b5/public/common/utils.py#L451)
with the more flexible [public/common_vis/utils.py visualize()](https://github.com/fusedio/udfs/blob/98263fcf8fdade1fd2e29a2c65ca5f494e2888b5/public/common_vis/utils.py#L3)

Occurrence of arr_to_plasma():
- [x] public/Landsat_Tile_Example/Landsat_Tile_Example.py 80c0a84
- [x] public/DSM_JAXA_Example/utils.py cb9516a
- [x] public/Solar_Irradiance/Solar_Irradiance.py 3f2a249
- [x] public/DEM_Tile_Example/DEM_Tile_Example.py ef42812
- [x] public/DEM_10m_Tile_Example/DEM_10m_Tile_Example.py bd950fd
- [x] public/DEM_Raster_to_Vector_Example/utils.py #352
- [x] public/HLS_Tile_Example/HLS_Tile_Example.py #338
- [x] public/DC_AOI_Example/utils.py #359
- [x] public/Sentinel_Tile_Example/Sentinel_Tile_Example.py #360
- [ ] files/NetCDF_File/netcdf_file.py

**Comment by tylere** [comment]
Unable to update netcdf_file.py without access to the netCDF files used for testing.
